### ISSUE TITLE
Vec evaluate fails for routes with function schemas defined

### ISSUE THREAD

**Issue by cysidron1** [aurelio-labs/semantic-router#184] opened 2024-03-04 03:08 UTC
https://github.com/aurelio-labs/semantic-router/blob/cbae899a136e8d8c4fb3f263e3a7f77ab949cdc7/semantic_router/layer.py#L478

This may be a misunderstanding on my part, but I have some dynamic routes defined that I am trying to fit to set of utterances using the routelayer fit method. It's failing here, with the error:

ValueError: Route has a function schema, but no text was provided.

Can someone provide guidance on whether this is a misuse of the dynamic routes on my part, or an actual bug?

**Comment by jamescalam** [comment] 2024-03-08 10:14
The problem is that we pass vectors (`Xq`) rather than text to speed up the evaluation process and ensure we only create embeddings once—this is an oversight on our part.

I think we can resolve this by modifying dynamic routes to be static within the evaluation flow — we will get the team working on it — thanks!

**Comment by Siraj-Aizlewood** [comment] 2024-03-12 09:37
This has been fixed in: https://github.com/aurelio-labs/semantic-router/pull/192

**Closed by Siraj-Aizlewood** 2024-03-12 09:37 UTC
Labels: bug
